- name: Install PowerDNS packages
  apt:
    name:
      - pdns-server
      - pdns-backend-mysql
    state: present
    update_cache: true

- name: Deploy PowerDNS configuration
  template:
    src: pdns.conf.j2
    dest: /etc/powerdns/pdns.conf

- name: Start and enable PowerDNS
  service:
    name: pdns
    state: started
    enabled: true
